import { ProjectPreview } from '@/components/project-preview';

const projects = [
  {name:'ContaNova',type:'GESTIÓN COMERCIAL · EN PRODUCCIÓN',text:'De las necesidades de un taller a una plataforma para varios negocios. Facturación electrónica SRI, clientes, productos, reportes y soporte continuo.',stack:'React / TypeScript / PostgreSQL',url:'https://contanova.org'},
  {name:'Taller Jeldes',type:'APLICACIÓN MÓVIL · USO INTERNO',text:'Reconstrucción en Flutter de la aplicación y el panel administrativo para 15 usuarios. Actividades, fotografías, asistencia e informes técnicos asistidos por IA.',stack:'Flutter / Dart / IA aplicada'},
  {name:'MxCorreo',type:'AUTOMATIZACIÓN · WINDOWS',text:'Aplicación portable para importar, depurar y clasificar contactos. Más de 36.000 registros procesados para Actuariosa, con detección de duplicados e informes. La revisión DNS no confirma la existencia de cada buzón.',stack:'Python / Tkinter / SQLite / DNS'},
  {name:'San Viernes & Billar Club',type:'SOFTWARE COMERCIAL · EN PRODUCCIÓN',text:'Dos implementaciones de gestión de ventas, tickets, compras e inventario. Aplicaciones de supervisión para propietarios y distribución remota de actualizaciones.',stack:'React / TypeScript / Electron / Capacitor'},
  {name:'SmartDocs',type:'GESTIÓN DOCUMENTAL · POR ENCARGO',text:'Almacenamiento, búsqueda, OCR, edición, historial de versiones y uso compartido para organizar documentos.',stack:'React / TypeScript / Tesseract.js',url:'https://smartdocs-phi.vercel.app'},
  {name:'TechView',type:'VISIÓN ARTIFICIAL · PROYECTO ACADÉMICO',text:'Desarrollé el software de unas gafas de asistencia visual con detección de objetos e indicaciones por voz. Proyecto en equipo reconocido con mención de honor en enero de 2026.',stack:'Python / OpenCV / YOLOv8 / Raspberry Pi',url:'https://github.com/FakeCxbas/TechView'},
  {name:'Strawberry Sweet Serve',type:'PEDIDOS · ADOPTADO POR EL NEGOCIO',text:'Prototipo funcional para digitalizar pedidos de un local de fresas con crema: personalización, panel administrativo y seguimiento de estados.',stack:'React / TypeScript'},
  {name:'Actuariosa Web',type:'SITIO WEB · PROPUESTA DE DEMOSTRACIÓN',text:'Propuesta de sitio para consultoría actuarial con servicios, preguntas frecuentes y solicitudes de cotización por WhatsApp y correo.',stack:'React / TypeScript / CSS adaptable',url:'https://github.com/FakeCxbas/actuariosa-web'},
];
export default function Home(){return <>
  <a className="skip" href="#contenido">Saltar al contenido</a>
  <header className="topbar"><a className="brand" href="#inicio" aria-label="Sebastián Zambrano, inicio">sz<span>.</span></a><nav aria-label="Navegación principal"><a href="#proyectos">Proyectos</a><a href="#sobre-mi">Sobre mí</a><a href="#trayectoria">Trayectoria</a><a href="#contacto">Contacto ↗</a></nav></header>
  <main id="contenido">
    <section className="hero" id="inicio"><div className="eyebrow"><span className="dot"/> GUAYAQUIL, ECUADOR <span className="hero-index">PORTAFOLIO / 2026</span></div><h1>Sebastián<br/>Zambrano<span className="period">.</span></h1><div className="hero-bottom"><h2>Software que sale<br/>del código <em>y se usa.</em></h2><div><p>Desarrollador de software junior. Creo aplicaciones web, móviles y de escritorio para resolver necesidades reales de negocios.</p><a className="primary-link" href="#proyectos">Explorar mis proyectos <span>↓</span></a></div></div><div className="hero-foot"><span>DESARROLLO · IMPLEMENTACIÓN · SOPORTE</span><span>React / TypeScript / Python / Flutter</span></div></section>
    <section className="projects section" id="proyectos"><div className="section-title"><span className="eyebrow">01 / TRABAJO SELECCIONADO</span><h2>De una necesidad<br/>a una solución.</h2><p>Proyectos comerciales, herramientas internas y exploraciones tecnológicas. Mi trabajo incluye entender el problema, desarrollar, capacitar y acompañar después de la entrega.</p></div><div className="project-grid">{projects.map((project,index)=><article className={`project project-${index}`} key={project.name}><ProjectPreview index={index}/><div className="project-meta"><span>{project.type}</span><span>{String(index+1).padStart(2,'0')}</span></div><h3>{project.name}</h3><p>{project.text}</p><div className="project-footer"><span>{project.stack}</span>{project.url&&<a href={project.url} target="_blank" rel="noopener noreferrer">{project.url.includes('github.com')?'Ver repositorio':'Visitar proyecto'} ↗</a>}</div></article>)}</div></section>
    <section className="about section" id="sobre-mi"><div><span className="eyebrow">02 / SOBRE MÍ</span><h2>Entender el negocio.<br/><em>Construir lo útil.</em></h2></div><div className="about-copy"><p>Mi experiencia no empezó solamente frente al código. He trabajado en atención al cliente, ventas, inventarios y asistencia administrativa. Conocer esos procesos me ayuda a desarrollar herramientas que encajan con el trabajo diario.</p><p>Estudio Ciencias de la Computación en la Universidad Espíritu Santo y trabajo de forma independiente en el desarrollo y soporte de aplicaciones. También colaboro con Actuariosa en herramientas internas, gestión de correo y apoyo actuarial.</p><p>Me interesa crecer en desarrollo de software y soporte de aplicaciones, en Guayaquil o de forma remota.</p><div className="skills"><div><h3>Desarrollo</h3><p>React, TypeScript, JavaScript, HTML, CSS, Python, Flutter y Dart.</p></div><div><h3>Datos y herramientas</h3><p>PostgreSQL, SQLite, APIs REST, Git, GitHub, Electron y Capacitor.</p></div><div><h3>También aporto</h3><p>Excel, organización documental, atención al cliente, capacitación y soporte remoto básico.</p></div><div><h3>Idiomas</h3><p>Español nativo e inglés intermedio.</p></div></div></div></section>
    <section className="section experience" id="trayectoria"><div className="section-title"><span className="eyebrow">03 / TRAYECTORIA</span><h2>Aprender haciendo.</h2></div><div className="timeline"><article><span>MAR. 2026 — ACTUALIDAD</span><div><h3>Desarrollo de software independiente</h3><p>Requerimientos, desarrollo, implementación, capacitación y mantenimiento para pequeños negocios.</p></div></article><article><span>MAR. 2025 — ACTUALIDAD</span><div><h3>Actuariosa</h3><p>Desarrollo de herramientas internas, automatización de correo y apoyo actuarial.</p></div></article><article><span>FEB. — ABR. 2026</span><div><h3>Electromecánica Bolívar</h3><p>Atención al cliente, venta de repuestos, facturación e inventario. El punto de partida de ContaNova.</p></div></article><article><span>FEB. — ABR. 2025</span><div><h3>Apol S.A.</h3><p>Prácticas de asistencia administrativa y de gerencia: reuniones, documentos, bases de datos y reportes.</p></div></article><article><span>FORMACIÓN</span><div><h3>Ciencias de la Computación · UEES</h3><p>En curso desde mayo de 2026. Modalidad virtual nocturna.</p><h3 className="education">Bachiller en Informática · Instituto Coello</h3><p>Marzo de 2026. Tutoría voluntaria de Matemáticas, Física y Computación durante los años lectivos 2023–2025.</p></div></article></div></section>
    <section className="contact section" id="contacto"><span className="eyebrow">04 / HABLEMOS</span><h2>¿Construimos<br/><em>lo siguiente?</em></h2><p>Oportunidades junior, pasantías remuneradas y proyectos de software.</p><a className="email" href="mailto:sebastianzambrano2818@gmail.com">sebastianzambrano2818@gmail.com ↗</a><div className="social"><a href="https://github.com/FakeCxbas" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/sebasti%C3%A1n-paul-zambrano-inga-7700633ab/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div></section>
  </main><footer className="footer"><span>© 2026 Sebastián Zambrano</span><span>Guayaquil, Ecuador</span><a href="#inicio">Volver arriba ↑</a></footer>
</>}
